//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 26/05/2024 18:12:35
//
//===========================================================================================
//
#pragma once

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"TRCheatWin"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"TRCheatWin (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"TRCheatWin (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"TRCheatWin"
#define PROGRAM_REGKEY  L"Macallan\\TRCheatWin"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\TRCheatWin"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "TRCheatWin"
#ifdef _WIN64
#define PROGRAM_NAME_P  "TRCheatWin (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "TRCheatWin (x86 MBCS)"
#endif
#define PROGRAM_SECT    "TRCheatWin"
#define PROGRAM_REGKEY  "Macallan\\TRCheatWin"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\TRCheatWin"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Sun May 26 18:12"
#define PROGRAM_DATE_F  L"Sun May 26 18:12 2024"
#define PROGRAM_YEAR    L"2024"
#define PROGRAM_TIME    L"2024/05/26 18:12:35"
#else
#define PROGRAM_DATE    "Sun May 26 18:12"
#define PROGRAM_DATE_F  "Sun May 26 18:12 2024"
#define PROGRAM_YEAR    "2024"
#define PROGRAM_TIME    "2024/05/26 18:12:35"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"4.1.10.005"
#define PROGRAM_INSTALL L"4.1.10005"
#define PROGRAM_VER_NUM 40110005
#define PROGRAM_BUILD   L"772"
#define PROGRAM_TITLE   L"TRCheat Win"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"TRCheat Win (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"TRCheat Win (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "4.1.10.005"
#define PROGRAM_INSTALL "4.1.10005"
#define PROGRAM_VER_NUM 40110005
#define PROGRAM_BUILD   "772"
#define PROGRAM_TITLE   "TRCheat Win"
#ifdef _WIN64
#define PROGRAM_TITLE_P "TRCheat Win (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "TRCheat Win (x86 MBCS)"
#endif
#endif

