//{{NO_DEPENDENCIES}}
// Fichier Include généré de Microsoft Visual C++.
// Utilisé par TRCheatWin.rc
//
#define _USING_V110_SDK71_              1
#define IDCANCEL2                       3
#define ID_WALKTHRU                     3
#define IDM_ABOUTBOX                    0x0010
#define IDM_REMASTERED                  0x0020
#define IDM_STANDARD                    0x0030
#define IDM_UNCHECKED                   0x0040
#define IDM_SEARCH_EXT                  0x0050
#define IDM_VERTICALVIEW                0x0060
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TR3CHEATWIN_DIALOG          102
#define IDS_REMASTERED                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_STANDARD                    104
#define IDS_UNCHECKED                   105
#define IDS_SEARCH_EXT                  106
#define IDM_AMMOS                       107
#define IDS_VERTICALVIEW                107
#define IDM_EQUIPMENT                   108
#define IDS_DARK_THEME                  108
#define IDM_GUN                         109
#define IDS_SEARCH_POS_EXT              109
#define IDM_ITEMS                       110
#define IDS_DARK_FULL                   110
#define IDS_STRING111                   111
#define IDM_SEARCH_POS_EXT              0x0070
#define IDS_LOG_TRACE                   112
#define IDD_TRXDIABLOGBASE              114
#define IDD_TRXMAPAREAS                 115
#define IDD_TRXALLMAPS                  116
#define IDD_TRXVERTICALMAP              118
#define IDD_TRXMESSAGEBOX               120
#define IDD_TRXHELPDIALOG               121
#define IDD_TRXLEVELS                   125
#define IDM_DARK_THEME                  0x0080
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     132
#define IDB_BITMAP2                     133
#define IDB_CHRONO                      135
#define IDB_DESERT_EAGLE_2              137
#define IDB_DESERT_EAGLE_3              138
#define IDB_DESERT_EAGLE                139
#define IDB_FLARES_2                    140
#define IDB_FLARES                      141
#define IDB_GRENADE_LAUNCHER_2          142
#define IDB_GRENADE_LAUNCHER_3          143
#define IDB_GRENADE_LAUNCHER            144
#define IDM_DARK_FULL                   0x0090
#define IDB_GUNS                        145
#define IDB_HARPOON_2                   146
#define IDB_HARPOON_3                   147
#define IDB_HARPOON                     148
#define IDB_LARGE_MEDIPAK_2             149
#define IDB_LARGE_MEDIPAK_3             150
#define IDB_LARGE_MEDIPAK               151
#define IDB_RIOT_GUN_2                  153
#define IDB_RIOT_GUN                    154
#define IDB_ROCKET_LAUNCHER_2           155
#define IDB_ROCKET_LAUNCHER             156
#define IDB_SMALL_MEDIPAK_2             157
#define IDB_SMALL_MEDIPAK_3             158
#define IDB_SMALL_MEDIPAK               159
#define IDB_UZIS_2                      160
#define IDM_LOG_TRACE                   0x00A0
#define IDB_UZIS                        161
#define IDB_MP5                         162
#define IDD_GUN_PAGE                    166
#define IDD_EQUIPMENT                   169
#define IDD_INFO                        170
#define IDD_ITEMS                       171
#define IDD_AMMOS                       175
#define IDB_AMMOS_DESERT_EAGLE          176
#define IDB_AMMOS_GRENADES              177
#define IDB_AMMOS_HARPOON               178
#define IDB_AMMOS_RIOTGUN               179
#define IDB_AMMOS_MP5                   180
#define IDB_AMMOS_UZIS                  181
#define IDB_AMMOS_ROCKET                183
#define IDB_LEVEL_0                     184
#define IDB_LEVEL_1                     185
#define IDB_LEVEL_2                     186
#define IDB_LEVEL_TR3                   187
#define IDB_LEVEL_3                     188
#define IDB_LEVEL_4                     189
#define IDB_LEVEL_5                     190
#define IDB_LEVEL_6                     191
#define IDB_LEVEL_7                     192
#define IDB_LEVEL_8                     193
#define IDB_LEVEL_9                     194
#define IDB_LEVEL_10                    195
#define IDB_LEVEL_11                    196
#define IDB_LEVEL_12                    197
#define IDB_LEVEL_13                    198
#define IDB_LEVEL_14                    199
#define IDB_LEVEL_15                    200
#define IDB_LEVEL_16                    201
#define IDB_LEVEL_17                    202
#define IDB_LEVEL_18                    203
#define IDB_LEVEL_19                    204
#define IDB_ANTARC                      205
#define IDB_INDIA                       206
#define IDB_LONDON                      207
#define IDB_NEVADA                      208
#define IDB_SOUTHPAC                    209
#define IDB_THEEND                      210
#define IDB_T1                          211
#define IDB_T2                          213
#define IDB_T3                          214
#define IDB_T4                          215
#define IDB_M1_MAP                      216
#define IDB_KEY1_1                      217
#define IDB_KEY1_2                      218
#define IDB_KEY1_3                      219
#define IDB_KEY1_4                      220
#define IDB_KEY1_5                      221
#define IDB_KEY1_6                      223
#define IDB_KEY1_7                      224
#define IDB_KEY1_8                      225
#define IDB_KEY1_9                      226
#define IDB_KEY1_10                     227
#define IDB_KEY2_1                      228
#define IDB_KEY2_2                      229
#define IDB_KEY2_3                      230
#define IDB_KEY2_4                      231
#define IDB_KEY2_5                      232
#define IDB_KEY3_1                      233
#define IDB_KEY4_1                      234
#define IDB_KEY4_2                      235
#define IDB_KEY4_3                      237
#define IDB_P1_2                        238
#define IDB_P1_1                        239
#define IDB_P1_3                        240
#define IDB_P1_4                        241
#define IDB_P1_5                        242
#define IDB_P1_6                        243
#define IDB_P2_1                        244
#define IDB_P2_2                        245
#define IDB_P2_3                        246
#define IDB_P3_1                        247
#define IDB_P3_2                        248
#define IDB_P4_1                        249
#define IDB_P4_2                        250
#define IDB_TR2_END                     252
#define IDB_TR2_START                   253
#define IDB_TR1_END                     254
#define IDB_TR1_START                   255
#define IDB_TUB_END                     256
#define IDB_TUB_START                   257
#define IDB_CROWBAR                     258
#define IDB_REVOLVER                    259
#define IDB_HK                          261
#define IDB_CROSSBOW                    262
#define IDB_AMMOS_HK                    263
#define IDB_AMMOS_REVOLVER              264
#define IDB_BITMAP3                     265
#define IDB_AMMOS_ARROW                 265
#define IDB_AMMOS_GUNS                  266
#define IDB_CHRONICLES_0                267
#define IDB_CHRONICLES_1                268
#define IDB_LAST_REV_0                  269
#define IDB_BITMAP4                     270
#define IDB_LAST_REV_1                  270
#define IDD_ITEMS1                      272
#define IDD_REMASTERED                  272
#define IDD_REMASTERED_123              272
#define IDD_ITEMS_TR4                   273
#define IDD_LIST_SECRETS                274
#define IDD_REMASTERED_INFO             275
#define IDR_MENU_LIST                   276
#define IDD_DIFFERENCES                 277
#define IDD_POSITION                    278
#define IDB_GRAPPLING                   279
#define IDD_REMASTERED1                 279
#define IDD_REMASTERED_456              279
#define IDB_BITMAP5                     280
#define IDB_AMMOS_GRAP                  280
#define IDD_ITEMS_TRR456                280
#define IDR_HELPTEXT1                   282
#define IDR_HELP_TEXT                   282
#define IDI_ICON1                       283
#define IDI_CHECK                       283
#define IDI_CHECK_WHITE                 283
#define IDI_CHECK_BLACK                 284
#define IDI_CLOSE                       285
#define IDI_MAXIMIZE                    286
#define IDI_MINIMIZE                    287
#define IDI_ICON2                       288
#define IDI_WINDOWED                    288
#define IDR_MENU_ITEMS                  289
#define IDI_ICOPY                       292
#define IDI_COPY                        292
#define IDI_PASTE                       293
#define IDI_PASTE_BLACK                 295
#define IDI_ICON3                       296
#define IDI_COPY_BLACK                  296
#define IDR_MENU1                       297
#define IDR_DLGMENU1                    298
#define IDI_ICON4                       298
#define IDI_SEARCH_BLACK                298
#define IDI_SEARCH_WHITE                299
#define IDI_SORT_WHITE                  300
#define IDI_SORT_BLACK                  301
#define IDI_LOAD_BLACK                  302
#define IDI_LOAD_WHITE                  303
#define IDI_SAVE_BLACK                  304
#define IDI_SAVE_WHITE                  305
#define IDI_REFRESH_BLACK               306
#define IDI_ICON6                       307
#define IDI_REFRESH_WHITE               307
#define IDR_HELPTEXT2                   308
#define IDR_TR1CHEATS                   308
#define IDR_TR2CHEATS                   310
#define IDR_TR3CHEATS                   312
#define IDR_TR4CHEATS                   313
#define IDR_RCDATA1                     314
#define IDR_TR6CHEATS                   314
#define IDC_DESERTEAGLE                 1001
#define IDC_ITEM_02                     1002
#define IDC_CROWBAR                     1002
#define IDC_GUNS                        1003
#define IDC_CROWBAR2                    1003
#define IDC_HEADSET                     1003
#define IDC_UZI                         1004
#define IDC_RIOTGUN                     1005
#define IDC_MP5                         1006
#define IDC_HARPOON                     1007
#define IDC_GRENADELAUNCHER             1008
#define IDC_HARPOON2                    1008
#define IDC_GUN                         1008
#define IDC_ROCKETLAUNCHER              1009
#define IDC_HEALTH                      1010
#define IDC_AROCKETLAUNCHER             1011
#define IDC_XHEALTH                     1011
#define IDC_AGRENADELAUNCHER            1012
#define IDC_OBJ_1                       1012
#define IDC_AHARPOON                    1013
#define IDC_AMP5                        1014
#define IDC_XHARPOON                    1014
#define IDC_ARIOTGUN                    1015
#define IDC_AUZIS                       1016
#define IDC_AM16                        1016
#define IDC_ADESERTEAGLE                1017
#define IDC_AGRENADE                    1017
#define IDC_ITEM_01                     1018
#define IDC_ARIOTGUN2                   1018
#define IDC_AROCKET                     1018
#define IDC_FLARES                      1019
#define IDC_AHARPOON2                   1019
#define IDC_SMALLPAK                    1019
#define IDC_LARGEMEDIPAK                1020
#define IDC_AHARPOON3                   1020
#define IDC_FLARE                       1020
#define IDC_SMALLMEDIPAK                1021
#define IDC_AGRENADELAUNCHER2           1021
#define IDC_XRIOTGUN                    1021
#define IDC_AIR                         1022
#define IDC_AGRENADELAUNCHER3           1022
#define IDC_XM16                        1022
#define IDC_DIRECTORY                   1023
#define IDC_XGRENADE                    1023
#define IDC_AGUNS                       1023
#define IDC_LEVELNAME                   1024
#define IDC_XROCKET                     1024
#define IDC_ITEM_03                     1025
#define IDC_KEY_1                       1025
#define IDC_ITEM_04                     1026
#define IDC_KEY_2                       1026
#define IDC_KEY1                        1027
#define IDC_KEY_3                       1027
#define IDC_FILENAMES                   1028
#define IDC_KEY_4                       1028
#define IDC_FILENAME                    1029
#define IDC_LEVELNUMBER                 1030
#define IDC_OBJ_2                       1030
#define IDC_KEY2                        1031
#define IDC_OBJ_3                       1031
#define IDC_KEY3                        1032
#define IDC_OBJ_4                       1032
#define IDC_KEY4                        1033
#define IDC_DEFAULT                     1033
#define IDC_NKEY4                       1034
#define IDC_VAIR                        1034
#define IDC_AIR_REM                     1034
#define IDC_NKEY3                       1035
#define IDC_AIR_REM2                    1035
#define IDC_STATE                       1035
#define IDC_NKEY2                       1036
#define IDC_XHEALTH2                    1036
#define IDC_REAL_HEALTH                 1036
#define IDC_NKEY1                       1037
#define IDC_MAP_1                       1037
#define IDC_NITEM_4                     1038
#define IDC_MAP_2                       1038
#define IDC_NITEM_3                     1039
#define IDC_FLARE2                      1039
#define IDC_COL_CRYSTAL                 1039
#define IDC_NITEM_2                     1040
#define IDC_HEALTH2                     1040
#define IDC_SAVE                        1040
#define IDC_NITEM_1                     1041
#define IDC_TRE_1                       1041
#define IDC_MAP2                        1042
#define IDC_TRE_2                       1042
#define IDC_MAP1                        1043
#define IDC_TRE_3                       1043
#define IDC_UNLIMITED                   1044
#define IDC_TRE_4                       1044
#define IDC_SECRETS                     1045
#define IDC_TREASURE1                   1046
#define IDC_LARA                        1046
#define IDC_SECRETS2                    1046
#define IDC_NB_SECRETS                  1046
#define IDC_SECRETS_1                   1046
#define IDC_TREASURE2                   1047
#define IDC_NB_SECRETS2                 1047
#define IDC_SECRETS_2                   1047
#define IDC_TREASURE3                   1048
#define IDC_SECRETS_3                   1048
#define IDC_SECRETS_MAX                 1048
#define IDC_TREASURE4                   1049
#define IDC_PICKUP_MAX                  1049
#define IDC_NTREASURE4                  1050
#define IDC_NTREASURE3                  1051
#define IDC_CRISTAL_MAX                 1051
#define IDC_NTREASURE2                  1052
#define IDC_CRISTAL_MAX2                1052
#define IDC_KILLS_MAX                   1052
#define IDC_NTREASURE1                  1053
#define IDC_NBSECRETS                   1054
#define IDC_STATUS                      1055
#define IDC_NMAP2                       1056
#define IDC_STATUS2                     1056
#define IDC_NMAP1                       1057
#define IDC_LOAD                        1058
#define IDC_SAVENUMBER                  1059
#define IDC_LARABURNING                 1060
#define IDC_REFRESH                     1061
#define IDC_WRITE                       1062
#define IDC_ALL                         1063
#define IDC_MAX                         1063
#define IDC_REFRESH2                    1064
#define IDC_REMOVE                      1064
#define IDC_MAX_ONE                     1064
#define IDC_REMOVE_LOC                  1065
#define IDC_REMOVE2                     1065
#define IDC_SORT                        1065
#define IDC_MAX_ONE2                    1066
#define IDC_TR3                         1066
#define IDC_SET                         1066
#define IDC_SHOW                        1067
#define IDC_LEVEL_PICTURE               1068
#define IDC_RESET_ALL                   1068
#define IDC_MAX2                        1068
#define IDC_RESET                       1068
#define IDC_DRACMAN                     1069
#define IDC_LEVEL_PLACE                 1069
#define IDC_RESET2                      1069
#define IDC_RESETGAME                   1069
#define IDC_MACALLAN                    1070
#define IDC_JOURNAL                     1070
#define IDC_LISTCTRL                    1072
#define IDC_DEF_ADDRESS                 1073
#define IDC_JOURNAL2                    1073
#define IDC_SHELL                       1073
#define IDC_CRIOTGUN                    1079
#define IDC_CGRENADELAUNCHER            1080
#define IDC_CHARPOON                    1081
#define IDC_CDESERTEAGLE                1082
#define IDC_CMP5                        1083
#define IDC_CUZIS                       1084
#define IDC_CROCKETLAUNCHER             1085
#define IDC_UNFINITE_AIR                1086
#define IDC_CGUNS                       1086
#define IDC_BUT_SMEDI                   1087
#define IDC_BUT_LMEDI                   1088
#define IDC_BUT_FLARES                  1089
#define IDC_LIFE                        1090
#define IDC_GOD                         1091
#define IDC_LASER                       1092
#define IDC_EMAIL                       1093
#define IDC_BINOCULAR                   1093
#define IDC_VERSION                     1094
#define IDC_COPYRIGHT                   1095
#define IDC_WEB                         1097
#define IDC_BM_RIOTGUN                  1098
#define IDC_WEB2                        1098
#define IDC_OSVER                       1098
#define IDC_BM_DESERTEAGLE              1099
#define IDC_BM_UZIS                     1100
#define IDC_BM_GRENADE                  1101
#define IDC_BM_MP5                      1102
#define IDC_BM_ROCKET                   1103
#define IDC_BM_ARROW                    1104
#define IDC_BM_GUNS                     1105
#define IDC_BM_HARPOON                  1106
#define IDC_NKEY1_SPIN                  1109
#define IDC_NKEY2_SPIN                  1110
#define IDC_COMBO1                      1110
#define IDC_COMBO                       1110
#define IDC_AREAS                       1110
#define IDC_LEVEL_TOP                   1110
#define IDC_CUSTOM_COMBO                1110
#define IDC_NKEY3_SPIN                  1111
#define IDC_LEVEL_TOP2                  1111
#define IDC_LEVEL_BOTTOM                1111
#define IDC_NKEY4_SPIN                  1112
#define IDC_NITEM_1_SPIN                1113
#define IDC_NITEM_2_SPIN                1114
#define IDC_MAGNUM                      1114
#define IDC_NMAP1_SPIN                  1115
#define IDC_AMAGNUM                     1115
#define IDC_NMAP2_SPIN                  1116
#define IDC_XMAGNUM                     1116
#define IDC_NITEM_3_SPIN                1117
#define IDC_M16                         1117
#define IDC_NITEM_4_SPIN                1118
#define IDC_GRENADE                     1118
#define IDC_NTREASURE1_SPIN             1119
#define IDC_ROCKET                      1119
#define IDC_NTREASURE2_SPIN             1120
#define IDC_N_OBJ_1                     1120
#define IDC_NTREASURE3_SPIN             1121
#define IDC_AUZI                        1121
#define IDC_NTREASURE4_SPIN             1122
#define IDC_LARGEPAK                    1122
#define IDC_XUZI                        1123
#define IDC_N_OBJ_2                     1124
#define IDC_N_OBJ_3                     1125
#define IDC_N_OBJ_4                     1126
#define IDC_N_KEY_1                     1127
#define IDC_N_KEY_2                     1128
#define IDC_N_KEY_3                     1129
#define IDC_N_KEY_4                     1130
#define IDC_AR_FULL                     1131
#define IDC_AR_INFINITE                 1132
#define IDC_N_MAP_1                     1133
#define IDC_LIST_ALL                    1134
#define IDC_UPDATE                      1135
#define IDC_CHECK1                      1136
#define IDC_BURNING                     1136
#define IDC_DONT_SHOW                   1136
#define IDC_ONE                         1137
#define IDC_ZERO                        1138
#define IDC_FOUR                        1139
#define IDC_STRONG                      1140
#define IDC_N_KEY_6                     1141
#define IDC_N_MAP_2                     1141
#define IDC_ITEM_5                      1141
#define IDC_ITEM_05                     1141
#define IDC_ITEM_6                      1142
#define IDC_ITEM_06                     1142
#define IDC_PICKUP                      1142
#define IDC_ITEM_7                      1143
#define IDC_ITEM_07                     1143
#define IDC_CRYSTAL                     1143
#define IDC_ITEM_8                      1144
#define IDC_ITEM_08                     1144
#define IDC_CRYSTAL2                    1144
#define IDC_KILL                        1144
#define IDC_ITEM_9                      1145
#define IDC_ITEM_09                     1145
#define IDC_N_TRE_1                     1145
#define IDC_ITEM_10                     1146
#define IDC_N_TRE_2                     1146
#define IDC_ITEM_11                     1147
#define IDC_N_TRE_3                     1147
#define IDC_ITEM_12                     1148
#define IDC_N_KEY_9                     1148
#define IDC_N_TRE_4                     1148
#define IDC_ITEM_13                     1149
#define IDC_UZI_CLIP                    1149
#define IDC_ITEM_14                     1150
#define IDC_M16_CLIP                    1150
#define IDC_NITEM5                      1151
#define IDC_NITEM_05                    1151
#define IDC_M16_CLIP2                   1151
#define IDC_GRENADE_CLIP                1151
#define IDC_NITEM6                      1152
#define IDC_NITEM_06                    1152
#define IDC_NITEM7                      1153
#define IDC_NITEM_07                    1153
#define IDC_NITEM8                      1154
#define IDC_NITEM_08                    1154
#define IDC_NITEM9                      1155
#define IDC_NITEM_09                    1155
#define IDC_NITEM_10                    1156
#define IDC_NITEM_11                    1157
#define IDC_NITEM_12                    1158
#define IDC_NITEM_13                    1159
#define IDC_NITEM_14                    1160
#define IDC_NITEM_13_SPIN               1161
#define IDC_NITEM_14_SPIN               1162
#define IDC_NITEM5_SPIN                 1163
#define IDC_NITEM6_SPIN                 1164
#define IDC_NITEM7_SPIN                 1165
#define IDC_NITEM8_SPIN                 1166
#define IDC_NITEM9_SPIN                 1167
#define IDC_NITEM_10_SPIN               1168
#define IDC_NITEM_11_SPIN               1169
#define IDC_NITEM_12_SPIN               1170
#define IDC_ITEM_15                     1171
#define IDC_NITEM_15                    1172
#define IDC_NITEM_15_SPIN               1173
#define IDC_ITEM_16                     1174
#define IDC_NITEM_16                    1175
#define IDC_NITEM_16_SPIN               1176
#define IDC_ITEM_17                     1177
#define IDC_ITEM_18                     1178
#define IDC_ITEM_19                     1179
#define IDC_ITEM_20                     1180
#define IDC_NITEM_17                    1181
#define IDC_NITEM_17_SPIN               1182
#define IDC_NITEM_18                    1183
#define IDC_NITEM_18_SPIN               1184
#define IDC_NITEM_19                    1185
#define IDC_NITEM_19_SPIN               1186
#define IDC_NITEM_20                    1187
#define IDC_NITEM_20_SPIN               1188
#define IDC_ITEM_21                     1189
#define IDC_ITEM_22                     1190
#define IDC_ITEM_23                     1191
#define IDC_ITEM_24                     1192
#define IDC_NITEM_21                    1193
#define IDC_NITEM_21_SPIN               1194
#define IDC_NITEM_22                    1195
#define IDC_NITEM_22_SPIN               1196
#define IDC_NITEM_23                    1197
#define IDC_NITEM_23_SPIN               1198
#define IDC_NITEM_24                    1199
#define IDC_NITEM_24_SPIN               1200
#define IDC_ITEM_25                     1201
#define IDC_ITEM_26                     1202
#define IDC_ITEM_27                     1203
#define IDC_ITEM_28                     1204
#define IDC_NITEM_25                    1205
#define IDC_NITEM_25_SPIN               1206
#define IDC_NITEM_26                    1207
#define IDC_NITEM_26_SPIN               1208
#define IDC_NITEM_27                    1209
#define IDC_NITEM_27_SPIN               1210
#define IDC_NITEM_28                    1211
#define IDC_NITEM_28_SPIN               1212
#define IDC_NITEM_01                    1213
#define IDC_NITEM_02                    1214
#define IDC_NITEM_03                    1215
#define IDC_NITEM_04                    1216
#define IDC_LIST_SECRETS                1217
#define IDC_ITEM_29                     1217
#define IDC_TR1_PLUS                    1218
#define IDC_NITEM_29                    1218
#define IDC_TR2_PLUS                    1219
#define IDC_NITEM_28_SPIN2              1219
#define IDC_NITEM_29_SPIN               1219
#define IDC_TR3_PLUS                    1220
#define IDC_GAME_PLUS                   1221
#define IDC_KILL_WILLARD                1223
#define IDC_TEXT                        1224
#define IDC_INFO                        1224
#define IDC_BUTTON3                     1225
#define IDC_RENUM                       1225
#define IDC_REMOVE_CUSTOM               1225
#define IDC_ALL_AMMOS                   1225
#define IDC_TRNG_GODRESET               1225
#define IDC_DELETE                      1226
#define IDC_DIFFERENCES                 1226
#define IDC_BUTTON1                     1227
#define IDC_SECRET_ALL                  1227
#define IDC_SEARCH                      1227
#define IDC_NORTH                       1227
#define IDC_FROM_NORTH                  1227
#define IDC_ZRIOTGUN                    1227
#define IDC_ALL_GUNS                    1227
#define IDC_FULL                        1227
#define IDC_ITEMS                       1227
#define IDC_LBL_OBJ_1                   1228
#define IDC_BUTTON2                     1228
#define IDC_MAP                         1228
#define IDC_SOUTH                       1228
#define IDC_FROM_SOUTH                  1228
#define IDC_ZMP5                        1228
#define IDC_TRNG_GUNS                   1228
#define IDC_LBL_OBJ_3                   1229
#define IDC_ZHARPOON                    1229
#define IDC_TRNG_GUNS2                  1229
#define IDC_TRNG_GODMODE                1229
#define IDC_LBL_KEY_1                   1230
#define IDC_ZDESERT                     1230
#define IDC_TRNG_DOORS                  1230
#define IDC_LBL_KEY_3                   1231
#define IDC_ZGRENADE                    1231
#define IDC_TRNG_DOORS2                 1231
#define IDC_TRNG_ENEMIES                1231
#define IDC_LBL_MAP_1                   1232
#define IDC_ZUZI                        1232
#define IDC_LBL_TRE_1                   1233
#define IDC_ZROCKET                     1233
#define IDC_LBL_TRE_3                   1234
#define IDC_EDIT1                       1234
#define IDC_WEST_EAST                   1234
#define IDC_WEST                        1234
#define IDC_HELP_TEXT                   1234
#define IDC_FROM_WEST                   1234
#define IDC_ZGUNS                       1234
#define IDC_MESSAGE                     1235
#define IDC_VERTICAL                    1235
#define IDC_EAST                        1235
#define IDC_PICTURE                     1236
#define IDC_SOUTH_NORTH                 1236
#define IDC_ORIENTATION                 1237
#define IDC_ROOM                        1237
#define IDC_LIST2                       1238
#define IDC_SPECIAL                     1238
#define IDC_ROOM2                       1238
#define IDC_DIRECTION                   1238
#define IDC_CHECK2                      1239
#define IDC_RECURSE                     1239
#define IDC_WORD5                       1239
#define IDC_CHECK3                      1240
#define IDC_WORD3                       1240
#define IDC_WEST_EAST_M                 1241
#define IDC_VERTICAL_M                  1242
#define IDC_SOUTH_NORTH_M               1243
#define IDC_ORIENTATION_D               1244
#define IDC_SPECIAL2                    1245
#define IDC_SPECIAL_X                   1245
#define IDC_WORD5_X                     1246
#define IDC_WORD3_X                     1247
#define IDC_WORD2                       1248
#define IDC_WORD2_X                     1249
#define IDC_WORD0                       1250
#define IDC_WORD2_X2                    1251
#define IDC_WORD0_X                     1251
#define IDC_EDIT2                       1252
#define IDC_WEST_EAST_OLD               1252
#define IDC_AREA                        1252
#define IDC_VERTICAL_OLD                1253
#define IDC_SOUTH_NORTH_OLD             1254
#define IDC_WORD0_OLD                   1255
#define IDC_ORIENTATION_OLD             1256
#define IDC_WORD2_OLD                   1257
#define IDC_WORD3_OLD                   1258
#define IDC_SPECIAL_OLD                 1259
#define IDC_WORD5_OLD                   1260
#define IDC_WEST_EAST_RANGE             1261
#define IDC_VERTICAL_RANGE              1262
#define IDC_SOUTH_NORTH_OLD2            1263
#define IDC_SOUTH_NORTH_RANGE           1263
#define IDC_RANGES                      1264
#define IDC_POSITION                    1265
#define IDC_EDIT3                       1266
#define IDC_CURRENT                     1266
#define IDC_POSITION2                   1266
#define IDC_SHOW_MAP                    1266
#define IDC_AREA_INFOS                  1266
#define IDC_VERSIONS                    1267
#define IDC_FRAME_POSITION              1268
#define IDC_ADD_CUSTOM                  1269
#define IDC_BUTTON4                     1270
#define IDC_SEE_CUSTOM                  1270
#define IDC_FROM_EAST                   1272
#define IDC_SCROLLBAR1                  1273
#define IDC_HELP_SCROLL                 1273
#define IDC_SQUARE                      1274
#define IDC_COPYPOS                     1275
#define IDC_PASTEPOS                    1276
#define IDC_LEVEL_LIST                  1276
#define IDC_COPYPOS2                    1277
#define IDC_BUTTON5                     1277
#define IDC_LEVELS                      1277
#define IDC_POS_LABEL                   1278
#define IDC_ROOM_SEARCH                 1279
#define IDC_LEFT                        1280
#define IDC_RIGHT                       1281
#define IDC_TR4_PLUS                    1282
#define IDC_TR5_PLUS                    1283
#define IDC_TR6_PLUS                    1284
#define IDC_KILL_BOSS                   1285
#define IDC_ROOM_BUT                    1286
#define ID_MENULIST_EXPORT              32771
#define ID_MENULIST_IMPORT              32772
#define ID_MENULIST_DELETE              32773
#define ID_MENULIST_INFOS               32774
#define ID_MENULIST_RENUMBER            32775
#define ID_MENULIST_RESETTO             32776
#define ID_MENULIST_RESETTOSTART        32777
#define ID_MENULIST_POSITION            32778
#define ID_ITEMS                        32779
#define ID_ITEMS_ITEM1                  32780
#define ID_ITEMS_ITEM2                  32781
#define ID_ITEMS_ITEM3                  32782
#define ID_ITEMS_ITEM4                  32783
#define ID_ITEMS_ITEM5                  32784
#define ID_ITEMS_ITEM6                  32785
#define ID_ITEMS_ITEM7                  32786
#define ID_ITEMS_ITEM8                  32787
#define ID_SYSMENU_CLOSE                32795
#define ID_SYSTEMMENU_RESTORE           32801
#define ID_SYSTEMMENU_MOVE              32802
#define ID_SYSTEMMENU_MINIMIZE          32803
#define ID_SYSTEMMENU_ABOUTTOMBRAIDERCHEATPROGRAM 32804
#define ID_SYSTEMMENU_REMASTEREDTOMBRAIDER 32805
#define ID_SYSTEMMENU_STANDARDTOMBRAIDER 32806
#define ID_SYSTEMMENU_SEARCHEXTENDED    32807
#define ID_SYSTEMMENU_SEARCHPOSITIONEXTENDED 32808
#define ID_SYSTEMMENU_DARKTHEME         32809
#define ID_SYSTEMMENU_DARKTHEMEFULL     32810
#define ID_SYSTEMMENU_UNHECKED          32811
#define ID_SYSMENU_ABOUTTOMBRAIDERCHEATPROGRAM 32815
#define ID_SYSTEMMENU_SIZE              32824
#define ID_SYSTEMMENU_MAXIMIZE          32826
#define ID_DIALOGMENU_VERTICALVIEW      32828
#define ID_ITEMS_ID                     32830
#define ID_ITEMS_ALL                    32831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        315
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1287
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
