//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 02/06/2024 08:33:26
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"ReadTR2"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"ReadTR2 (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"ReadTR2 (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"ReadTR2"
#define PROGRAM_REGKEY  L"Macallan\\ReadTR2"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\ReadTR2"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "ReadTR2"
#ifdef _WIN64
#define PROGRAM_NAME_P  "ReadTR2 (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "ReadTR2 (x86 MBCS)"
#endif
#define PROGRAM_SECT    "ReadTR2"
#define PROGRAM_REGKEY  "Macallan\\ReadTR2"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\ReadTR2"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Sun Jun 02 08:33"
#define PROGRAM_DATE_F  L"Sun Jun 02 08:33 2024"
#define PROGRAM_YEAR    L"2024"
#define PROGRAM_TIME    L"2024/06/02 08:33:26"
#else
#define PROGRAM_DATE    "Sun Jun 02 08:33"
#define PROGRAM_DATE_F  "Sun Jun 02 08:33 2024"
#define PROGRAM_YEAR    "2024"
#define PROGRAM_TIME    "2024/06/02 08:33:26"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"4.1.11.010"
#define PROGRAM_INSTALL L"4.1.11010"
#define PROGRAM_VER_NUM 40111010
#define PROGRAM_BUILD   L"385"
#define PROGRAM_TITLE   L"Read TR2"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"Read TR2 (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"Read TR2 (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "4.1.11.010"
#define PROGRAM_INSTALL "4.1.11010"
#define PROGRAM_VER_NUM 40111010
#define PROGRAM_BUILD   "385"
#define PROGRAM_TITLE   "Read TR2"
#ifdef _WIN64
#define PROGRAM_TITLE_P "Read TR2 (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "Read TR2 (x86 MBCS)"
#endif
#endif

#endif

