//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2025 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 27/02/2025 09:30:26
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"ReadTR2"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"ReadTR2 (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"ReadTR2 (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"ReadTR2"
#define PROGRAM_REGKEY  L"Macallan\\ReadTR2"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\ReadTR2"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "ReadTR2"
#ifdef _WIN64
#define PROGRAM_NAME_P  "ReadTR2 (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "ReadTR2 (x86 MBCS)"
#endif
#define PROGRAM_SECT    "ReadTR2"
#define PROGRAM_REGKEY  "Macallan\\ReadTR2"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\ReadTR2"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Thu Feb 27 09:30"
#define PROGRAM_DATE_F  L"Thu Feb 27 09:30 2025"
#define PROGRAM_YEAR    L"2025"
#define PROGRAM_TIME    L"2025/02/27 09:30:26"
#else
#define PROGRAM_DATE    "Thu Feb 27 09:30"
#define PROGRAM_DATE_F  "Thu Feb 27 09:30 2025"
#define PROGRAM_YEAR    "2025"
#define PROGRAM_TIME    "2025/02/27 09:30:26"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"4.6.04.001"
#define PROGRAM_INSTALL L"4.6.04001"
#define PROGRAM_VER_NUM 40604001
#define PROGRAM_BUILD   L"745"
#define PROGRAM_TITLE   L"Read TR2"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"Read TR2 (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"Read TR2 (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "4.6.04.001"
#define PROGRAM_INSTALL "4.6.04001"
#define PROGRAM_VER_NUM 40604001
#define PROGRAM_BUILD   "745"
#define PROGRAM_TITLE   "Read TR2"
#ifdef _WIN64
#define PROGRAM_TITLE_P "Read TR2 (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "Read TR2 (x86 MBCS)"
#endif
#endif

#endif

