#include "stdafx.h"
#include <Windows.h>

#include "TR4NG.h"

//
/////////////////////////////////////////////////////////////////////////////
//
/////////////////////////////////////////////////////////////////////////////
const char *GetTRNGTagLabel(WORD byte)
{
#define _casetostring(value) case value : return #value;

    switch ( byte )
    {
        _casetostring(NGTAG_NON_USATO)
        _casetostring(NGTAG_ANIMATED_TEXTURES)
        _casetostring(NGTAG_OLD_EFFECTS)
        _casetostring(NGTAG_OLD_FMV)
        _casetostring(NGTAG_REMAP_OBJ)
        _casetostring(NGTAG_SALVA_COORDINATE)
        _casetostring(NGTAG_PROGR_ACTIONS)
        _casetostring(NGTAG_OLD_ACTIONS)
        _casetostring(NGTAG_EXTRA_INFO_ROOMS)
        _casetostring(NGTAG_LANGUAGE_STRINGS)
        _casetostring(NGTAG_SCRIPT_OPTIONS)
        _casetostring(NGTAG_SCRIPT_LEVEL)
        _casetostring(NGTAG_FLAG_LEVEL_TR4)
        _casetostring(NGTAG_OLD_CONDITION)
        _casetostring(NGTAG_VARIABLE_DATA)
        _casetostring(NGTAG_PUSH_CLIMB)
        _casetostring(NGTAG_PRINT_STRING)
        _casetostring(NGTAG_ELEVATORS)
        _casetostring(NGTAG_MIRRORS)
        _casetostring(NGTAG_BLIND_SAVE)
        _casetostring(NGTAG_CASUALE)
        _casetostring(NGTAG_CONTROLLO_OPTIONS)
        _casetostring(NGTAG_TEX_PARZIALE)
        _casetostring(NGTAG_REMAP_TAILS)
        _casetostring(NGTAG_SWAP_MESH)
        _casetostring(NGTAG_STATUS_GTRIGGERS)
        _casetostring(NGTAG_ROOM_FLAGS)
        _casetostring(NGTAG_WEATHER_INTENSITY)
        _casetostring(NGTAG_STATUS_ORGANIZER)
        _casetostring(NGTAG_IMPORT_FILE)
        _casetostring(NGTAG_INDICI_PFRAME)
        _casetostring(NGTAG_REMAP_STATICS)
        _casetostring(NGTAG_SALVA_STATICS)
        _casetostring(NGTAG_SALVA_TIMER_OGGETTI)
        _casetostring(NGTAG_VERSION_HEADER)
        _casetostring(NGTAG_TOM_VERSION)
        _casetostring(NGTAG_STATUS_ANIM_RANGES)
        _casetostring(NGTAG_SAVEGAME_INFOS)
        _casetostring(NGTAG_MINI_SHOT)
        _casetostring(NGTAG_LEVEL_NAMES)
        _casetostring(NGTAG_NG_HUB_HEADERS)
        _casetostring(NGTAG_VAR_DATA_LARA)
        _casetostring(NGTAG_VET_REMAP_ROOMS)
        _casetostring(NGTAG_VAR_GLOBAL_TRNG)
        _casetostring(NGTAG_VAR_LOCAL_TRNG)
        _casetostring(NGTAG_FROZEN_ITEMS)
        _casetostring(NGTAG_SAVE_LOCUST)
        _casetostring(NGTAG_NO_COLL_ITEMS)
        _casetostring(NGTAG_SLOT_NAMES)
        _casetostring(NGTAG_FISH)
        _casetostring(NGTAG_STATUS_TRIGGER_GROUP)
        _casetostring(NGTAG_ADAPTIVE_FARVIEW)
        _casetostring(NGTAG_KAYAK_EXTRA_DATA)
        _casetostring(NGTAG_ASSIGNED_SLOT)
        _casetostring(NGTAG_DIARY_DATA)
        _casetostring(NGTAG_ANIM_SWAPPING)
        _casetostring(NGTAG_FLIP_MESH)
        _casetostring(NGTAG_PLUGIN_DATA)
        _casetostring(NGTAG_PLUGIN_NAMES_NGLE)
        _casetostring(NGTAG_PLUGIN_ID_FLOOR_TABLE)
        _casetostring(NGTAG_EXTRA_AI_RECORDS)
        _casetostring(NGTAG_CUTSCENE_CAMERA)
        _casetostring(NGTAG_ACTORS_INDICES)
        _casetostring(NGTAG_SLOT_FLAGS_ARRAY)
        _casetostring(NGTAG_OCB_ITEMS)
        _casetostring(NGTAG_REMAP_PLUGIN_IDS)
        _casetostring(NGTAG_SWAP_SINGLE_MESH)
        _casetostring(NGTAG_NEW_CAMERAS)
        _casetostring(NGTAG_SLOT_INFO)
    }

    return "MGTAB_Unknown";
}

//
/////////////////////////////////////////////////////////////////////////////
//
/////////////////////////////////////////////////////////////////////////////
const char *GetTRNGCntLabel(WORD byte)
{
    switch ( byte )
    {
        _casetostring(cnt_AssignSlot)	
        _casetostring(cnt_Snow)		
        _casetostring(cnt_LevelFarView)
        _casetostring(cnt_FogRange)	
        _casetostring(cnt_WorldFarView)
        _casetostring(cnt_TextFormat)
        _casetostring(cnt_Rain)		
        _casetostring(cnt_Damage)
        _casetostring(cnt_Enemy)
        _casetostring(cnt_Animation)
        _casetostring(ctn_MirrorEffect)
        _casetostring(ctn_Elevator)
        _casetostring(ctn_KeyPad)
        _casetostring(ctn_AddEffect)
        _casetostring(ctn_Detector)
        _casetostring(ctn_Settings)
        _casetostring(ctn_TextureSequence)
        _casetostring(ctn_Equipment)
        _casetostring(ctn_MultEnvCondition)
        _casetostring(ctn_Customize)
        _casetostring(ctn_TriggerGroup)
        _casetostring(ctn_GlobalTrigger)
        _casetostring(ctn_Organizer)
        _casetostring(ctn_SoundSettings)
        _casetostring(ctn_ItemGroup)
        _casetostring(ctn_ColorRGB)
        _casetostring(ctn_Parameters)
        _casetostring(ctn_Turbo)
        _casetostring(ctn_WindowTitle)
        _casetostring(ctn_TestPosition)
        _casetostring(ctn_LogItem)
        _casetostring(ctn_WindowsFont)
        _casetostring(ctn_Diary)
        _casetostring(ctn_Image)
        _casetostring(ctn_SavegamePanel)
        _casetostring(cnt_DiagnosticType)
        _casetostring(cnt_Switch)
        _casetostring(cnt_CombineItems)
        _casetostring(cnt_StandBy)
        _casetostring(cnt_AnimationObj)
        _casetostring(cnt_DefaultWindowsFont)
        _casetostring(cnt_Demo)
        _casetostring(cnt_Plugin)
        _casetostring(cnt_LaraStartPos)
        _casetostring(cnt_StaticMIP)
        _casetostring(cnt_TriggerGroupWord)
        _casetostring(cnt_FlagsOption)
        _casetostring(cnt_FlagsLevel)
    }
    return "cnt_Unknown";
}

