//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2025 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 24/05/2025 16:35:27
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"Analyze"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"Analyze (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"Analyze (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"Analyze"
#define PROGRAM_REGKEY  L"Macallan\\Analyze"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\Analyze"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "Analyze"
#ifdef _WIN64
#define PROGRAM_NAME_P  "Analyze (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "Analyze (x86 MBCS)"
#endif
#define PROGRAM_SECT    "Analyze"
#define PROGRAM_REGKEY  "Macallan\\Analyze"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\Analyze"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Sat May 24 16:35"
#define PROGRAM_DATE_F  L"Sat May 24 16:35 2025"
#define PROGRAM_YEAR    L"2025"
#define PROGRAM_TIME    L"2025/05/24 16:35:27"
#else
#define PROGRAM_DATE    "Sat May 24 16:35"
#define PROGRAM_DATE_F  "Sat May 24 16:35 2025"
#define PROGRAM_YEAR    "2025"
#define PROGRAM_TIME    "2025/05/24 16:35:27"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"4.7.02.004"
#define PROGRAM_INSTALL L"4.7.02004"
#define PROGRAM_VER_NUM 40702004
#define PROGRAM_BUILD   L"1085"
#define PROGRAM_TITLE   L"Analyze"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"Analyze (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"Analyze (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "4.7.02.004"
#define PROGRAM_INSTALL "4.7.02004"
#define PROGRAM_VER_NUM 40702004
#define PROGRAM_BUILD   "1085"
#define PROGRAM_TITLE   "Analyze"
#ifdef _WIN64
#define PROGRAM_TITLE_P "Analyze (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "Analyze (x86 MBCS)"
#endif
#endif

#endif

