//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 18/05/2024 11:49:25
//
//===========================================================================================
//
#ifndef AUTOMATICVERSIONHEADER
#define AUTOMATICVERSIONHEADER

#ifdef UNICODE
#define	PROGRAM_MAIL	L"mailto:ian.macallan@gmail.com"
#define	PROGRAM_HTTP	L"https://www.macallan.org/"
#define	PROGRAM_DWNL	L"https://home.macallan.org:9443/"
#define	PROGRAM_WIKI	L"https://www.macallan.org/"
#define	PROGRAM_FORUM	L"https://www.macallan.org/"
#define	PROGRAM_MMSFAQ	L"https://www.macallan.org/"
#define	PROGRAM_RSS		L"index.php?title=Special:Recentchanges&feed=rss"
#define	PROGRAM_NEWS	L"news://home.macallan.org/macallan.mail.solution"
#define	PROGRAM_SITE	L"www.macallan.org"
#define	PROGRAM_NAME	L"Analyze"
#ifdef _WIN64
#define	PROGRAM_NAME_P	L"Analyze (x64 Unicode)"
#else
#define	PROGRAM_NAME_P	L"Analyze (x86 Unicode)"
#endif
#define	PROGRAM_SECT	L"Analyze"
#define	PROGRAM_REGKEY	L"Macallan\\Analyze"
#define	PROGRAM_SOFTKEY	L"SOFTWARE\\Macallan\\Analyze"
#define	PROGRAM_CHARS	L"Unicode"
#else
#define	PROGRAM_MAIL	"mailto:ian.macallan@gmail.com"
#define	PROGRAM_HTTP	"https://www.macallan.org/"
#define	PROGRAM_DWNL	"https://home.macallan.org:9443/"
#define	PROGRAM_WIKI	"https://www.macallan.org/"
#define	PROGRAM_FORUM	"https://www.macallan.org/"
#define	PROGRAM_MMSFAQ	"https://www.macallan.org/"
#define	PROGRAM_RSS		"index.php?title=Special:Recentchanges&feed=rss"
#define	PROGRAM_NEWS	"news://home.macallan.org/macallan.mail.solution"
#define	PROGRAM_SITE	"www.macallan.org"
#define	PROGRAM_NAME	"Analyze"
#ifdef _WIN64
#define	PROGRAM_NAME_P	"Analyze (x64 MBCS)"
#else
#define	PROGRAM_NAME_P	"Analyze (x86 MBCS)"
#endif
#define	PROGRAM_SECT	"Analyze"
#define	PROGRAM_REGKEY	"Macallan\\Analyze"
#define	PROGRAM_SOFTKEY	"SOFTWARE\\Macallan\\Analyze"
#define	PROGRAM_CHARS	"MBCS"
#endif

#ifdef UNICODE
#define	PROGRAM_DATE	L"Sat May 18 11:49"
#define	PROGRAM_DATE_F	L"Sat May 18 11:49 2024"
#define	PROGRAM_YEAR	L"2024"
#define	PROGRAM_TIME	L"2024/05/18 11:49:25"
#else
#define	PROGRAM_DATE	"Sat May 18 11:49"
#define	PROGRAM_DATE_F	"Sat May 18 11:49 2024"
#define	PROGRAM_YEAR	"2024"
#define	PROGRAM_TIME	"2024/05/18 11:49:25"
#endif

#ifdef UNICODE
#define	PROGRAM_VERSION	L"4.1.07.008"
#define	PROGRAM_INSTALL	L"4.1.07008"
#define	PROGRAM_VER_NUM	40107008
#define	PROGRAM_BUILD	L"583"
#define	PROGRAM_TITLE	L"Analyze"
#ifdef _WIN64
#define	PROGRAM_TITLE_P	L"Analyze (x64 Unicode)"
#else
#define	PROGRAM_TITLE_P	L"Analyze (x86 Unicode)"
#endif
#else
#define	PROGRAM_VERSION	"4.1.07.008"
#define	PROGRAM_INSTALL	"4.1.07008"
#define	PROGRAM_VER_NUM	40107008
#define	PROGRAM_BUILD	"583"
#define	PROGRAM_TITLE	"Analyze"
#ifdef _WIN64
#define	PROGRAM_TITLE_P	"Analyze (x64 MBCS)"
#else
#define	PROGRAM_TITLE_P	"Analyze (x86 MBCS)"
#endif
#endif

#endif
